### ISSUE TITLE
Warn user when saving contents of XQuery window with non-.xq* file extension

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#126]
In [a stackoverflow thread](http://stackoverflow.com/questions/38359614/improve-performance-of-query-with-range-indexes-in-exist-db/38361339), the user who posted the question and I determined that the reason his indexes weren't being applied was that he had saved the collection.xconf file from an XQuery window (started via "New XQuery") in eXide. As a result, the file's mimetype was not XML, eXide didn't offer to save the index in `/db/system`, and he was extremely confused. 

A warning should appear when saving the contents of an XQuery window with a non-`.xq*` filename, prompting the user to consider copying and pasting the file into a new window using the "New" button instead of the "New XQuery" window and selecting the appropriate file type.

**Comment by antonioaltamura** [comment]
Actually I'm found confusing several things. You should provide a sample xml here  http://exist-db.org/exist/apps/doc/newrangeindex.xml.
The fist question I posted to myself "where I define the path of the fields I want to index if there is no trace in .xconf file?" How can I be sure the index is correctly defined on my xml? just from Monex? It looks like the last step to me..
Now I know the path isn't a problem since I ended indexing all the fields with the name "number" no matter the path :)
