### ISSUE TITLE
With configuration.xml set to guest=no, login is impossible

### ISSUE THREAD

**Issue by joewiz** [eXist-db/eXide#164]
In my testing of @line-o's https://github.com/eXist-db/eXide/pull/142, setting `guest=no` prevents users from even getting to the page where they would log in.  I propose reverting this PR and restoring the ability of users to access the log in page so that they can authenticate.

**Comment by joewiz** [comment]
As the eXide docs state, the purpose of `guest=no` is:

> **guest=yes|no**: if set to "no", the default guest user will not be able to log in. eXide will thus always show a login window before the editor is loaded - unless you already provided credentials during a previous, still valid session. eXide will thus always show a login window before the editor is loaded

#142 prevented the login window being shown.

The docs above could be clarified a bit.  Instead of this:

> if set to "no", the default guest user will not be able to log in

This should be revised to:

> if set to "no", the default guest user will not be able to access eXide without first logging in via eXide or another application sharing the same session.

**Comment by rvdb** [comment]
This is an annoying bug, making it impossible to use `guest=no`, which I don't like in production environments.

If https://github.com/wolfgangmm/eXide/pull/142 is intended to prevent users from authenticating via eXide itself, while instead having them authenticate via other apps such as the dashboard, I think the `local:user-allowed()` function should check against session attributes instead of request attributes. I've tried to explain this a bit in the context of the code here: https://github.com/wolfgangmm/eXide/pull/142/files#r149674898.

Tested locally, changing the `request:get-attribute("org.exist.login.user")` calls to `session:get-attribute("org.exist.login.user")` makes it possible again to log in via the dashboard and get access to eXide.

**Comment by dscheuneman** [comment]
Just noting that this is still a problem.  `guest=no` means nobody can use eXide, and so the documentation on this feature, which states that users will be prompted with a login window, is misleading.

Changing "request" to "session" in controller.xql, as suggested by rvdb above, works for me as a temporary fix, to allow a dashboard-logged-in user to access eXide, but eXide only gives an error screen if logged out.

The current URL of the pull is https://github.com/eXist-db/eXide/pull/142.  And see: https://exist-db.org/exist/apps/eXide/docs/doc.html#security.

**Comment by line-o** [comment]
I just ran into this issue again with eXist-6.2.0 and eXide-3.5.0 using a current version of Chrome without extensions.

**Comment by line-o** [comment]
As I was the one introducing this issue I will have a look if I can get rid of it as well.
