### ISSUE TITLE
[BUG] Issue in exporting my app to .xar file

### ISSUE THREAD

**Issue by Alexandros81** [eXist-db/eXide#649]
**Describe the bug**
With eXistdb 6.2.0 it seems the exporting within eXide to .xar file of my application is no more available.

**Expected behavior**
When I click on "Application" menu and "Download app" my expectation would be that of being able to download a ".xar" file, whereas I get only a ".zip" file, which later (even if renamed to a ".xar" file) cannot be uploaded through  the Package Manager of the Dashboard. By contrast I have no issues in completing the task ( download of the ".xar" file of my app) with eXist 6.1.0

**Comment by line-o** [comment]
Thanks for reporting this, @Alexandros81 
Since the issue you are describing is a problem with eXide could you reopen this issue there, please? https://github.com/exist-db/eXide/issues

Please also add the version of eXide you used when it was working and the version where it did not.

**Comment by Alexandros81** [comment]
Ah, OK, my fault, sorry. I'll reopen the issue there, thanks.

**Comment by Alexandros81** [comment]
However, I've checked and the eXide version is the same one: 3.5.0

**Comment by line-o** [comment]
Interesting! Ok, we will leave it open then.

**Comment by joewiz** [comment]
The latest release of eXide is 3.5.1, though I don't think anything changed in this respect from 3.5.0.

**Comment by Alexandros81** [comment]
Still working on the comprehention of the issue, but after updating to eXide 3.5.1, though still getting a .zip file instead of a .xar one, after renaming it to .xar, I was succesful in installing the app...

**Comment by Alexandros81** [comment]
Well, I think I have to speak with our server-expert guys, because it seems that the issue arises only while using the eXistdb instance installed on the debian OS we have on our central server. From there I cannot update the OS itself nor eXist's packages..., like if the internet connection were not available anymore.

**Comment by gmella** [comment]
I'm running eXide 2.4.9 on eXistDB 6.2.0 and get on my disk the app archive with .xar extension. On another instance with the same browser eXide 3.5.1 and eXisDB 6.2.0 I get .zip extensions. It seems related to firefox as seen on https://stackoverflow.com/questions/65398445/firefox-84-0-is-changing-custom-file-extension-from-downloaded-file

Response Headers are the same for what seem related to this issue. 

On another side,  trying to download from a direct url changes the behaviour
http://localhost:8080/exist/apps/eXide/modules/deployment.xq?download=true&collection=/db/apps/eXide/modules&indent=true&expand-xincludes=false&omit-xml-declaration=false works perfectly on both instances.

I did try tto remove the download attribute on the a link that may generate this conflict : https://github.com/eXist-db/eXide/blob/develop/src/deployment.js#L241 
But my javascript is not taken into account by my browsers (Firefox or Chrome / Linux) :(
Hope it helps.

**Comment by daliboris** [comment]
I think the problem is in [deployment.js](https://github.com/eXist-db/eXide/blob/2442c0bf6ebd42782e74a5db945f5c2345428513/src/deployment.js#L233C58-L233C68) file which calls [deployment.xq](https://github.com/eXist-db/eXide/blob/2442c0bf6ebd42782e74a5db945f5c2345428513/modules/deployment.xq#L588C1-L588C1) function `deploy:download`.

The name and extenstion of the generated file depends on the `$expathConf` parameter. 


```xquery
    let $name := 
        if ($expathConf) then
            concat($expathConf/@abbrev, "-", $expathConf/@version, ".xar")
        else
            replace($collection, "^.+/([^/]+)$", "$1") || ".zip"
```

But this parameter is not set in [deployment.js](https://github.com/eXist-db/eXide/blob/2442c0bf6ebd42782e74a5db945f5c2345428513/src/deployment.js#L233C58-L233C68).

```javascript
const url = "modules/deployment.xq?download=true&collection=" + encodeURIComponent(collection) + "&indent=" + indentOnDownloadPackage + "&expand-xincludes=" + expandXIncludesOnDownloadPackage + "&omit-xml-declaration=" + omitXMLDeclatarionOnDownloadPackage;
```

The code has [changed](https://github.com/eXist-db/eXide/commit/5c92e44573a0b3ff539db604394f729c0d5ae86e) between versions 3.5.0 and 3.5.1.

**Comment by gmella** [comment]
I had a look on this point and $name was properly retrieved with a xar extension. But yes deployement.js changed and fetching method add the download attribute that take priority on the retrieved name. And this makes the name resolution less reliable if you ask to download an app looking on a file which is in a deeper level. I get src.zip trying to get exide.xar when I edit deployement.js
I do also think that the problem is in deployement.js but didn't figure to test my code changes :(

**Comment by joewiz** [comment]
Reverting [the change to deployment.js](https://github.com/eXist-db/eXide/commit/5c92e44573a0b3ff539db604394f729c0d5ae86e#diff-91477a7994e6a61cd33d52d0dd39905f2c00b13d81008d19aa7bf29d46082c71L218-R230) does fix *this issue*, but doing so would then break the ["download collections as zip" feature](https://github.com/eXist-db/eXide/pull/484) added by the commit, since using File > Manage > Download on a collection will then cause the .xar to be downloaded instead of a .zip file containing the selected collection. Clearly, that change conflated the two behaviors, since the two actions - downloading the current file's parent package vs. downloading the selected collection - are actually distinct. (Ideally, the solution would add tests, since these haven't been present.)

**Comment by joewiz** [comment]
I see how to approach this fix. The .zip download facility should be moved out of deployment.xq and into load.xq, and then the change to deployment.js can be safely reverted, with a slight adjustment to eXide.js.
